# Generated by Django 3.1 on 2020-08-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idTipoDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='id',
            new_name='idPersona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='documento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='idTipoDocumento',
            field=models.ForeignKey(db_column='idTipoDocumento', null=True, on_delete=django.db.models.deletion.RESTRICT, to='principal.tipodocumento'),
        ),
        migrations.AddField(
            model_name='persona',
            name='lugarResidencia',
            field=models.ForeignKey(db_column='idCiudad', null=True, on_delete=django.db.models.deletion.RESTRICT, to='principal.ciudad'),
        ),
    ]
