# Generated by Django 3.1 on 2020-08-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20200812_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='persona',
            name='lugarResidencia',
            field=models.ForeignKey(blank=True, db_column='idCiudad', null=True, on_delete=django.db.models.deletion.RESTRICT, to='principal.ciudad'),
        ),
    ]
