# Generated by Django 3.1 on 2020-08-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20200813_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
